name: campus_fitness_app
description: A campus fitness app that allows students to track gym busyness and access personalized workout and nutrition plans.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation - Updated to a more recent version
  go_router: ^16.0.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Charts and Visualizations
  fl_chart: ^1.0.0
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  
  # Animations
  lottie: ^3.3.1
  
  # Responsive UI
  flutter_screenutil: ^5.9.0
  
  # Local Notifications
  flutter_local_notifications: ^19.3.0
  
  # Firebase
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  firebase_analytics: ^11.5.0
  
  # Additional utilities for Firebase
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
