// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWwZwAE4SeQe7ERYsfUpwKjN9xrjXMQJU',
    appId: '1:377595243502:web:61f903b03d01582b723cff',
    messagingSenderId: '377595243502',
    projectId: 'smartfitness-c99fa',
    authDomain: 'smartfitness-c99fa.firebaseapp.com',
    storageBucket: 'smartfitness-c99fa.firebasestorage.app',
    measurementId: 'G-1SKYVJMK2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOY8i0G3RWZKSF9boyAkADojFx1WUGLo',
    appId: '1:377595243502:android:c9aaa6739273d8dd723cff',
    messagingSenderId: '377595243502',
    projectId: 'smartfitness-c99fa',
    storageBucket: 'smartfitness-c99fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmAhPH93dRRwKPSYWrBe0FsP41LFqhy2w',
    appId: '1:377595243502:ios:fe63bfdea1ad3816723cff',
    messagingSenderId: '377595243502',
    projectId: 'smartfitness-c99fa',
    storageBucket: 'smartfitness-c99fa.firebasestorage.app',
    iosBundleId: 'com.example.campusFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmAhPH93dRRwKPSYWrBe0FsP41LFqhy2w',
    appId: '1:377595243502:ios:fe63bfdea1ad3816723cff',
    messagingSenderId: '377595243502',
    projectId: 'smartfitness-c99fa',
    storageBucket: 'smartfitness-c99fa.firebasestorage.app',
    iosBundleId: 'com.example.campusFitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWwZwAE4SeQe7ERYsfUpwKjN9xrjXMQJU',
    appId: '1:377595243502:web:5705b20a7c34915e723cff',
    messagingSenderId: '377595243502',
    projectId: 'smartfitness-c99fa',
    authDomain: 'smartfitness-c99fa.firebaseapp.com',
    storageBucket: 'smartfitness-c99fa.firebasestorage.app',
    measurementId: 'G-S9GG5T117R',
  );
}
